name: CI/CD - Manual Trigger

on:
    workflow_dispatch:
        inputs:
            annotation:
                description: 'Select Annotation (smoke or regression)'
                required: true
                default: 'smoke'
                options:
                    - smoke
                    - regression
            environment:
                description: 'Select Environment (stage or test)'
                required: true
                default: 'stage'
                options:
                    - stage
                    - test
            branch:
                description: 'Select Branch'
                required: true
                default: 'master'
                options:
                    - master
                    - feature/demo

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - - name: Checkout Repository
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.branch }}
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Cache JDK
              uses: actions/cache@v2
              with:
                  path: /usr/lib/jvm/java-11-openjdk-amd64
                  key: java-11-openjdk-amd64-${{ hashFiles('**/java-11-openjdk-amd64/**') }}
            - name: Install Maven
              run: |
                  sudo apt-get update 
                  sudo apt-get install -y maven
            - name: Cache Maven
              uses: actions/cache@v2
              with:
                  path: /usr/share/maven
                  key: maven-${{ hashFiles('**/usr/share/maven/**') }}
            - name: Run tests
              run: |
                  echo "Running Karate Tests..."  
                  mvn clean test -Dtest=TestRunner -Dannotation=${{ github.event.inputs.annotation }} -Denvironment=${{ github.event.inputs.environment }}